[build]
  publish = "public"
  command = "pip install -r netlify/functions/requirements.txt && echo 'Netlify build complete!'"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-python"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
